version: '3'
services:
  movies:
    image: ramu478/aws
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: ramu478/devops
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: ramu478/azure
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: ramu478/ds
    ports:
      - "83:80"
    deploy:
      replicas: 3


 
